set(CONFIG_BT_CENTRAL y)
set(CONFIG_BT_OBSERVER y)
set(CONFIG_BT_GATT_CLIENT y)
set(CONFIG_BT_SCAN_WITH_IDENTITY y)
set(CONFIG_BT_MAX_CONN 1)
set(CONFIG_BT_DEVICE_NAME "Pro2Dongle-BL616")
set(CONFIG_BT_DEVICE_NAME_DYNAMIC y)

set(CONFIG_BT_BREDR n)
set(CONFIG_BT_SDP n)
set(CONFIG_BT_A2DP n)
set(CONFIG_BT_AVRCP n)
set(CONFIG_BT_HFP n)
set(CONFIG_BT_STACK_CLI n)

set(CONFIG_GCC_COMPILE_LTO y)
set(CONFIG_USB_HS 1)
